name: Update Discord Bot Status

on:
  push:
    branches:
      - main

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run bot status updater
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Passa il token come variabile d'ambiente
          STATUS_MESSAGE: ${{ secrets.STATUS_MESSAGE }}  # Passa il messaggio come variabile d'ambiente
        run: |
          python main.py
